### PR TITLE
Update Content

### PR DESCRIPTION
**Pull request by Setnour6**
I like this mod, so I used tModPorter and tested changes to make it playable again and solve JIT errors

### CODE REVIEW

**Comment by LingASDJ** [comment]
Hi, Setnour6. Thank you very much for submitting this PR. There are currently not many improvements to this Mod, only some new weapon tag and some very supermodel weapons have been added.
Thank you for liking this Mod. I am also continuing to learn about TML, and I will merge this branch now. Additionally, I was quite busy a while ago, so I did not login to Github. Thank you again for your PR, Thanks!

**Comment by LingASDJ** [comment]
Hi Setnour6, do you know the pixel dungeon?
I am also a developer of PD Mod,
I am currently working on an event about Halloween,
I would like to invite you to help me create music for Halloween levels,
What do you think?
image

**Comment by Setnour6** [comment]
> Hi Setnour6, do you know the pixel dungeon? I am also a developer of PD Mod, I am currently working on an event about Halloween, I would like to invite you to help me create music for Halloween levels, What do you think? image

Hello. I would love to help but I am really busy at this time. Good luck on the event

**Comment by LingASDJ** [comment]
Don't worry, and thank you for your reply. Wishing you good luck every day, too.

**Pull request merged**
